### ISSUE TITLE
Ledger identifier

### ISSUE THREAD

**Issue by karimStekelenburg** [animo/anoncreds-interfaces#1]
How does the `AnonCredsIssuerService` know what ledger it should write the schema to?

https://github.com/animo/anoncreds-interfaces/blob/be2c77aeb7b1e5b64d4d9a232eacc1c4a2229954/src/services/AnonCredsIssuerServiceOptions.ts#L9-L13

**Comment by TimoGlastra** [comment]
The AnonCredsIssuerService doesn't write the schema to the ledger, it just creates the schema. Currently the IndyIssuerService also doesn't write to ledger, but rather that happens on a higher level
